[package]
name = "remote-externalities"
version = "0.1.0"
authors = ["kianenigma <kian.peymani@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
async-std = { version = "1.6.2" }
jsonrpsee = { version = "0.1.0", features = ["ws"] }
separator = "0.4.1"
ansi_term = "0.12.1"
env_logger = "0.7.1"
log = "0.4.8"

sub-storage = { path = "../sub-storage" }
sp-io = { path = "../../substrate/primitives/io" }
sp-core = { path = "../../substrate/primitives/core" }
sp-externalities = { path = "../../substrate/primitives/externalities" }

[dev-dependencies]
hex-literal = "0.2.1"
tokio-test = "0.2.1"
frame-system = { path = "../../substrate/frame/system" }
frame-support = { path = "../../substrate/frame/support" }
pallet-staking = { path = "../../substrate/frame/staking" }
sp-runtime = { path = "../../substrate/primitives/runtime" }



















